# Numpy Annotations

In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
x = np.array([1,2,3])
x

list1 = [1,2,3] # Lists may also be used as an ndarray
x = np.array(list1)
print(x)
print(type(x))


[1 2 3]
<class 'numpy.ndarray'>


# Numpy Data Types
https://numpy.org/doc/stable/user/basics.types.html

https://numpy.org/doc/stable/reference/arrays.dtypes.html#arrays-dtypes

In [9]:
x = np.array(list1, dtype = np.int8)

## Multidimensional Arrays

In [17]:
x = np.array([[1,2,3],[4,5,6]], np.uint8)
print(f"It has 2 entitites of 3 elements in it:", x.shape)
print(x)

It has 2 entitites of 3 elements in it: (2, 3)
[[1 2 3]
 [4 5 6]]


In [18]:
x[:,0] # Acessing the entire column

array([1, 4], dtype=uint8)

In [20]:
x[0,:] # Acessing the entire row

array([1, 2, 3], dtype=uint8)

In [22]:
x = np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]], np.uint8)

In [25]:
print(f"It has 2 arrays of 2 arrays with 3 elements in each one:", x.shape,"\n","It also has 3 dimensions.", x.ndim)
print(x)

It has 2 arrays of 2 arrays with 3 elements in each one: (2, 2, 3) 
 It also has 3 dimensions. 3
[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]]


# Numpy Methods

In [26]:
 print(x.shape, x.size, x.ndim,x.nbytes)

(2, 2, 3) 12 3 12


## Creating Matrices with ones and zeros

In [32]:
x = np.empty([3,3],np.uint8) # it creates an 3x3 array of random numbers

In [33]:
x

array([[240,   3,  65],
       [ 20, 128,   1],
       [  0,   0,   0]], dtype=uint8)

In [34]:
y = np.eye(5, dtype=np.uint8)

In [35]:
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

 ## Useful Numpy Operations


np.unique()
